parameters:
  jobName: release
  imageName: windows-2019
  displayName: 'Release Microsoft.PowerShell.SecretStore to NuGet'

jobs:
- job: ${{ parameters.jobName }}
  pool:
    vmImage: ${{ parameters.imageName }}
  displayName: ${{ parameters.displayName }}

  steps:
  - task: NuGetToolInstaller@1
    displayName: 'Install NuGet 5.6.0'
    inputs:
      checkLatest: false
      version: 5.6.0

  - task: DownloadBuildArtifacts@0
    displayName: 'Download SecretSTore module artifacts'
    inputs:
      buildType: current
      downloadType: specific
      artifactName: '**/*.nupkg'
      downloadPath: '$(System.ArtifactsDirectory)'

  - powershell: |
      Get-ChildItem '$(System.ArtifactsDirectory)/nupkg/Microsoft.PowerShell.SecretStore.*.nupkg' -ErrorAction SilentlyContinue
      # Get-ChildItem '$(System.ArtifactsDirectory)' -Recurse
    displayName: 'Capture SecretStore module NuGet package'

  # TODO: Need to create NuGet service connection
  #- task: NuGetCommand@2
  #  displayName: 'Push Microsoft.PowerShell.Store module artifacts to AzArtifactsFeed'
  #  inputs:
  #    command: push
  #    packagesToPush: '$(System.ArtifactsDirectory)/nupkg/Microsoft.PowerShell.SecretStore.*.nupkg'
  #    nuGetFeedType: external
  #    publishFeedCredentials: AzArtifactFeed

  #- task: NuGetCommand@2
    #  displayName: 'Push Microsoft.PowerShell.Store module artifacts to PSGallery feed'
    #  inputs:
    #    command: push
    #    packagesToPush: '$(System.ArtifactsDirectory)/nupkg/Microsoft.PowerShell.SecretStore.*.nupkg'
    #    nuGetFeedType: external
    #    publishFeedCredentials: PHPowerShellGalleryFeed
